import Foundation

extension Bundle {
    /// Resource bundle that resolves correctly in both `swift run` (dev)
    /// and `.app` (production) contexts.
    ///
    /// We can't use SwiftPM's auto-generated `Bundle.module` because its
    /// initializer is hard-coded to:
    ///
    ///     Bundle.main.bundleURL.appendingPathComponent("RefVault_RefVault.bundle")
    ///
    /// For a `.app`, `Bundle.main.bundleURL` returns the `.app` directory
    /// itself (e.g. `/Applications/RefVault.app/`), not `Contents/`. So
    /// the accessor expects the bundle at `RefVault.app/RefVault_RefVault.bundle`
    /// — the bundle root, outside `Contents/`. macOS bundle layout puts
    /// everything inside `Contents/`, and `codesign` refuses to sign a
    /// bundle that has anything at the root, so we can't put it where
    /// `Bundle.module` expects it.
    ///
    /// Instead the build script copies `RefVault_RefVault.bundle` into
    /// `Contents/Resources/` (the standard macOS location), and this
    /// accessor finds it there via `Bundle.main.resourceURL`.
    ///
    /// Falls back to `Bundle.module` for `swift run` dev sessions where
    /// `Bundle.main` doesn't have a resourceURL pointing at our resources.
    static let refvaultResources: Bundle = {
        // Production: .app with the SwiftPM bundle copied into
        // Contents/Resources/.
        if let resourceURL = Bundle.main.resourceURL {
            let nested = resourceURL.appendingPathComponent("RefVault_RefVault.bundle")
            if let bundle = Bundle(url: nested) {
                return bundle
            }
        }
        // Dev: `swift run` puts the bundle at .build/release/RefVault_RefVault.bundle.
        // Bundle.module's autogenerated path resolution works here.
        return .module
    }()
}
